### ISSUE TITLE
skip png, html .... files

### ISSUE THREAD

**Issue by SegFault42** [nyancrimew/goop#17]
Is there a way to skip all non essential files ?

**Comment by nyancrimew** [comment]
The idea of goop is to get as complete of a clone as possible. Also given how git works this isn't really possible and just restricting which files are downloaded for the missed/ignored files download bit only doesn't really make sense, especially since "non essential files" differs entirely on what you're trying to do.

If you are just doing simple bug bounty hunting and just want to see if grabbing git files is at all possible and do a very basic assessment then [arthaud/git-dumper](https://github.com/arthaud/git-dumper) is more than good enough for that and goop is total overkill.
